INSERT INTO plat (image, titre, description, prix, allergene, category) VALUES
('salade_vegetarienne.jpg', 'Salade Végétarienne', 'Salade verte, tomates, concombres, olives et vinaigrette balsamique.', 8.5, 'OEUF', 'VEGETARIEN'),
('steak_boeuf.jpg', 'Steak de Bœuf', 'Steak de bœuf grillé avec des herbes de Provence.', 15.5, 'GLUTEN', 'PROTEINE'),
('pasta_arachide.jpg', 'Pâtes à la Sauce Arachide', 'Pâtes au blé complet avec une sauce crémeuse à l’arachide.', 12.0, 'ARACHIDE', 'GRAS'),
('quiche_legumes.jpg', 'Quiche aux Légumes', 'Quiche aux légumes de saison, idéale pour un repas léger.', 10.0, 'GLUTEN', 'VEGETARIEN'),
('omelette_fromage.jpg', 'Omelette au Fromage', 'Omelette moelleuse au fromage cheddar et fines herbes.', 9.5, 'OEUF', 'PROTEINE'),
('avocado_toast.jpg', 'Avocado Toast', 'Pain grillé garni d’avocat écrasé, radis et graines de sésame.', 7.5, 'GLUTEN', 'VEGETARIEN'),
('poulet_curry.jpg', 'Poulet au Curry', 'Poulet mijoté dans une sauce au curry et lait de coco.', 14.0, 'OEUF', 'PROTEINE'),
('pizza_4fromages.jpg', 'Pizza Quatre Fromages', 'Pizza garnie de mozzarella, cheddar, bleu et parmesan.', 13.0, 'GLUTEN', 'GRAS'),
('salade_cesar.jpg', 'Salade César', 'Salade verte, poulet grillé, croûtons, parmesan et sauce César.', 11.5, 'OEUF', 'PROTEINE'),
('tarte_arachide_choco.jpg', 'Tarte Arachide Chocolat', 'Tarte sucrée avec une base d’arachide et nappage chocolat.',
